<a href="https://colab.research.google.com/github/Alejandroo04/Data-Science-Fundaments/blob/main/chapter_04/numpy_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Challenge

Create a NumPy ndarray object by using this list of numbers [7,8,4,5,1,2].


In [1]:
import numpy as np

numbers_list = [7, 8, 4, 5, 1, 2]
num_array = np.array(numbers_list)

print(num_array)


[7 8 4 5 1 2]


Using slicing print the elements from index 3 to the end of the array.



In [2]:
import numpy as np

numbers_list = [7, 8, 4, 5, 1, 2]
num_array = np.array(numbers_list)

sliced_array = num_array[3:]
print(sliced_array)


[5 1 2]


Using slicing print all the elements except the last one.



In [3]:
import numpy as np

numbers_list = [7, 8, 4, 5, 1, 2]
num_array = np.array(numbers_list)

sliced_array = num_array[:-1]
print(sliced_array)


[7 8 4 5 1]


Using slicing print the elements from index 1 to index 4 of the array.



In [4]:
import numpy as np

numbers_list = [7, 8, 4, 5, 1, 2]
num_array = np.array(numbers_list)

sliced_array = num_array[1:5]
print(sliced_array)


[8 4 5 1]


Reshape the array into a 3 rows and 2 cols (3,2).



In [5]:
import numpy as np

numbers_list = [7, 8, 4, 5, 1, 2]
num_array = np.array(numbers_list)

reshaped_array = num_array.reshape(3, 2)
print(reshaped_array)


[[7 8]
 [4 5]
 [1 2]]


Print all the array elements one by one (iterating).



In [6]:
import numpy as np

numbers_list = [7, 8, 4, 5, 1, 2]
num_array = np.array(numbers_list)

for element in num_array:
    print(element)


7
8
4
5
1
2


Create a new NumPy ndarray object by using this list of numbers [0,6,9].



In [7]:
import numpy as np

new_numbers_list = [0, 6, 9]
new_num_array = np.array(new_numbers_list)

print(new_num_array)


[0 6 9]


Join the two arrays.



In [8]:
import numpy as np

numbers_list = [7, 8, 4, 5, 1, 2]
new_numbers_list = [0, 6, 9]

num_array = np.array(numbers_list)
new_num_array = np.array(new_numbers_list)

concatenated_array = np.concatenate((num_array, new_num_array))
print(concatenated_array)


[7 8 4 5 1 2 0 6 9]


Using filtering print only the odd numbers of the joined array.



In [9]:
import numpy as np

numbers_list = [7, 8, 4, 5, 1, 2]
new_numbers_list = [0, 6, 9]

num_array = np.array(numbers_list)
new_num_array = np.array(new_numbers_list)

concatenated_array = np.concatenate((num_array, new_num_array))

odd_numbers = concatenated_array[concatenated_array % 2 != 0]
print(odd_numbers)


[7 5 1 9]


Sort the joined array elements.



In [10]:
import numpy as np

numbers_list = [7, 8, 4, 5, 1, 2]
new_numbers_list = [0, 6, 9]

num_array = np.array(numbers_list)
new_num_array = np.array(new_numbers_list)

concatenated_array = np.concatenate((num_array, new_num_array))

sorted_array = np.sort(concatenated_array)
print(sorted_array)


[0 1 2 4 5 6 7 8 9]


Store in an array the names of the months.



In [11]:
import numpy as np

months = np.array([
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
])

print(months)



['January' 'February' 'March' 'April' 'May' 'June' 'July' 'August'
 'September' 'October' 'November' 'December']


Split the months array in 4 periods of 3 elements each one.



In [12]:
import numpy as np

months = np.array([
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
])

split_periods = np.split(months, 4)

for period in split_periods:
    print(period)


['January' 'February' 'March']
['April' 'May' 'June']
['July' 'August' 'September']
['October' 'November' 'December']


Create an array with genre information ['F','M','F','F','M','F'].



In [13]:
import numpy as np

gender_array = np.array(['F', 'M', 'F', 'F', 'M', 'F'])

print(gender_array)


['F' 'M' 'F' 'F' 'M' 'F']


Find the indexes where the value is F.



In [14]:
import numpy as np

gender_array = np.array(['F', 'M', 'F', 'F', 'M', 'F'])

indexes_of_F = np.where(gender_array == 'F')[0]

print("Indexes where the value is 'F':", indexes_of_F)


Indexes where the value is 'F': [0 2 3 5]


Store in an array the age information [18,20,19,23,19,20].



In [15]:
import numpy as np

age_array = np.array([18, 20, 19, 23, 19, 20])

print(age_array)


[18 20 19 23 19 20]


Create a filter array with values < 20.



In [16]:
import numpy as np

age_array = np.array([18, 20, 19, 23, 19, 20])
filter_array = age_array < 20

print(filter_array)


[ True False  True False  True False]


Change the 3 index element with a value of 22



In [17]:
import numpy as np

age_array = np.array([18, 20, 19, 23, 19, 20])
age_array[3] = 22

print(age_array)


[18 20 19 22 19 20]


Print the 4 index element.

In [18]:
import numpy as np

age_array = np.array([18, 20, 19, 23, 19, 20])
element_at_index_4 = age_array[3]

print("Element at index 4:", element_at_index_4)


Element at index 4: 23
